extends RefCounted
class_name StructureIO

# 标准化学文件格式导入导出
# 支持: XYZ, PDB, CIF, POSCAR, SDF/MOL, LaH10-style JSON

# === XYZ 格式 ===
# 简单格式: 第1行=原子数, 第2行=注释, 之后每行=元素 x y z

static func export_xyz(atoms: Array, _bonds: Array, comment: String = "") -> String:
	var lines: Array = []
	lines.append(str(atoms.size()))
	lines.append(comment if comment else "Generated by CQM SuperCon Designer")
	for atom in atoms:
		var sym = _get_symbol(atom)
		var pos = _get_pos(atom)
		lines.append("%-2s %16.8f %16.8f %16.8f" % [sym, pos.x, pos.y, pos.z])
	return "\n".join(lines) + "\n"

static func import_xyz(text: String) -> Dictionary:
	var lines = text.strip_edges().split("\n")
	if lines.size() < 2:
		return {"error": "XYZ文件过短"}
	var n = int(lines[0].strip_edges())
	if n <= 0 or lines.size() < n + 2:
		return {"error": "XYZ原子数不匹配"}
	var atoms: Array = []
	for i in range(n):
		var parts = lines[i + 2].strip_edges().split_floats(" ", false)
		var sym_parts = lines[i + 2].strip_edges().split(" ", false)
		if sym_parts.is_empty() or parts.size() < 3:
			continue
		var sym = sym_parts[0].capitalize()
		atoms.append({
			"symbol": sym,
			"position": Vector3(parts[0], parts[1], parts[2])
		})
	return {"atoms": atoms, "bonds": []}

# === PDB 格式 ===
# 蛋白质数据库格式, 标准生物/化学结构

static func export_pdb(atoms: Array, bonds: Array, title: String = "CQM_STRUCTURE") -> String:
	var lines: Array = []
	lines.append("HEADER    %s" % title)
	lines.append("REMARK   Generated by CQM SuperCon Designer")
	lines.append("MODEL     1")
	for i in range(atoms.size()):
		var atom = atoms[i]
		var sym = _get_symbol(atom)
		var pos = _get_pos(atom)
		var element = sym.to_upper()
		var serial = (i + 1) % 100000
		lines.append("ATOM  %5d  %-3s MOL A   1    %8.3f%8.3f%8.3f  1.00  0.00          %-2s" % [
			serial, element, pos.x, pos.y, pos.z, element
		])
	lines.append("ENDMDL")
	for i in range(bonds.size()):
		var bond = bonds[i]
		var a_idx = _get_bond_atom_index(bond, 0)
		var b_idx = _get_bond_atom_index(bond, 1)
		if a_idx >= 0 and b_idx >= 0:
			lines.append("CONECT%5d%5d" % [a_idx + 1, b_idx + 1])
	lines.append("END")
	return "\n".join(lines) + "\n"

static func import_pdb(text: String) -> Dictionary:
	var lines = text.split("\n")
	var atoms: Array = []
	var bonds: Array = []
	for line in lines:
		var record = line.substr(0, 6).strip_edges() if line.length() >= 6 else ""
		if record == "ATOM" or record == "HETATM":
			if line.length() < 54:
				continue
			var sym = line.substr(76, 2).strip_edges() if line.length() >= 78 else line.substr(12, 3).strip_edges()
			sym = _normalize_element(sym)
			var x = float(line.substr(30, 8))
			var y = float(line.substr(38, 8))
			var z = float(line.substr(46, 8))
			atoms.append({"symbol": sym, "position": Vector3(x, y, z)})
		elif record == "CONECT":
			var parts = line.substr(6).strip_edges().split_floats(" ", false)
			if parts.size() >= 2:
				var a_idx = int(parts[0]) - 1
				for j in range(1, parts.size()):
					var b_idx = int(parts[j]) - 1
					if a_idx >= 0 and b_idx >= 0:
						bonds.append({"a": a_idx, "b": b_idx, "order": 1})
	return {"atoms": atoms, "bonds": bonds}

# === CIF 格式 (简化版) ===
# 晶体学信息框架, 用于周期性结构

static func export_cif(atoms: Array, _bonds: Array, cell_params: Dictionary = {}) -> String:
	var lines: Array = []
	lines.append("data_cqm_structure")
	lines.append("# Generated by CQM SuperCon Designer")
	lines.append("_audit_creation_date  %s" % Time.get_datetime_string_from_system())
	var a = cell_params.get("a", 10.0)
	var b = cell_params.get("b", 10.0)
	var c = cell_params.get("c", 10.0)
	var alpha = cell_params.get("alpha", 90.0)
	var beta = cell_params.get("beta", 90.0)
	var gamma = cell_params.get("gamma", 90.0)
	lines.append("_cell_length_a  %.6f" % a)
	lines.append("_cell_length_b  %.6f" % b)
	lines.append("_cell_length_c  %.6f" % c)
	lines.append("_cell_angle_alpha  %.6f" % alpha)
	lines.append("_cell_angle_beta  %.6f" % beta)
	lines.append("_cell_angle_gamma  %.6f" % gamma)
	lines.append("_symmetry_space_group_name_H-M  'P 1'")
	lines.append("_symmetry_Int_Tables_number  1")
	lines.append("loop_")
	lines.append("_symmetry_equiv_pos_site_id")
	lines.append("_symmetry_equiv_pos_as_xyz")
	lines.append("1  x,y,z")
	lines.append("loop_")
	lines.append("_atom_site_label")
	lines.append("_atom_site_type_symbol")
	lines.append("_atom_site_fract_x")
	lines.append("_atom_site_fract_y")
	lines.append("_atom_site_fract_z")
	for i in range(atoms.size()):
		var atom = atoms[i]
		var sym = _get_symbol(atom)
		var pos = _get_pos(atom)
		var fx = pos.x / a
		var fy = pos.y / b
		var fz = pos.z / c
		lines.append("%s%d  %s  %.6f  %.6f  %.6f" % [sym, i + 1, sym, fx, fy, fz])
	return "\n".join(lines) + "\n"

static func import_cif(text: String) -> Dictionary:
	var lines = text.split("\n")
	var atoms: Array = []
	var cell: Dictionary = {}
	var in_atom_loop = false
	var atom_col_map: Dictionary = {}
	var col_count = 0
	for line in lines:
		var stripped = line.strip_edges()
		if stripped.begins_with("_cell_length_a"):
			cell["a"] = float(stripped.split(" ", false)[1])
		elif stripped.begins_with("_cell_length_b"):
			cell["b"] = float(stripped.split(" ", false)[1])
		elif stripped.begins_with("_cell_length_c"):
			cell["c"] = float(stripped.split(" ", false)[1])
		elif stripped.begins_with("_cell_angle_alpha"):
			cell["alpha"] = float(stripped.split(" ", false)[1])
		elif stripped.begins_with("_cell_angle_beta"):
			cell["beta"] = float(stripped.split(" ", false)[1])
		elif stripped.begins_with("_cell_angle_gamma"):
			cell["gamma"] = float(stripped.split(" ", false)[1])
		elif stripped == "loop_":
			in_atom_loop = false
			atom_col_map.clear()
			col_count = 0
		elif stripped.begins_with("_atom_site_") and not in_atom_loop:
			if stripped.begins_with("_atom_site_type_symbol"):
				atom_col_map["symbol"] = col_count
			elif stripped.begins_with("_atom_site_fract_x"):
				atom_col_map["fx"] = col_count
			elif stripped.begins_with("_atom_site_fract_y"):
				atom_col_map["fy"] = col_count
			elif stripped.begins_with("_atom_site_fract_z"):
				atom_col_map["fz"] = col_count
			elif stripped.begins_with("_atom_site_Cartn_x"):
				atom_col_map["x"] = col_count
			elif stripped.begins_with("_atom_site_Cartn_y"):
				atom_col_map["y"] = col_count
			elif stripped.begins_with("_atom_site_Cartn_z"):
				atom_col_map["z"] = col_count
			col_count += 1
			in_atom_loop = true
		elif in_atom_loop and not stripped.begins_with("_") and not stripped.is_empty():
			var parts = stripped.split(" ", false)
			if parts.size() >= col_count and atom_col_map.has("symbol"):
				var sym = _normalize_element(parts[atom_col_map["symbol"]])
				var pos = Vector3.ZERO
				var a = cell.get("a", 1.0)
				var b = cell.get("b", 1.0)
				var c = cell.get("c", 1.0)
				if atom_col_map.has("x"):
					pos.x = float(parts[atom_col_map["x"]])
					pos.y = float(parts[atom_col_map["y"]])
					pos.z = float(parts[atom_col_map["z"]])
				elif atom_col_map.has("fx"):
					pos.x = float(parts[atom_col_map["fx"]]) * a
					pos.y = float(parts[atom_col_map["fy"]]) * b
					pos.z = float(parts[atom_col_map["fz"]]) * c
				atoms.append({"symbol": sym, "position": pos})
	return {"atoms": atoms, "bonds": [], "cell": cell}

# === POSCAR 格式 (VASP) ===
# 用于周期性DFT计算

static func export_poscar(atoms: Array, cell_params: Dictionary = {}, comment: String = "CQM Structure") -> String:
	var lines: Array = []
	lines.append(comment)
	var scale = cell_params.get("scale", 1.0)
	lines.append("%.6f" % scale)
	var a = cell_params.get("a", 10.0)
	var b = cell_params.get("b", 10.0)
	var c = cell_params.get("c", 10.0)
	lines.append("%.6f  0.000000  0.000000" % a)
	lines.append("0.000000  %.6f  0.000000" % b)
	lines.append("0.000000  0.000000  %.6f" % c)
	var type_counts: Dictionary = {}
	var type_order: Array = []
	for atom in atoms:
		var sym = _get_symbol(atom)
		if not type_counts.has(sym):
			type_counts[sym] = 0
			type_order.append(sym)
		type_counts[sym] += 1
	lines.append("  ".join(type_order))
	var count_strs: Array = []
	for s in type_order:
		count_strs.append(str(type_counts[s]))
	lines.append("  ".join(count_strs))
	lines.append("Cartesian")
	for s in type_order:
		for atom in atoms:
			if _get_symbol(atom) == s:
				var pos = _get_pos(atom)
				lines.append("%.6f  %.6f  %.6f" % [pos.x, pos.y, pos.z])
	return "\n".join(lines) + "\n"

static func import_poscar(text: String) -> Dictionary:
	var lines = text.strip_edges().split("\n")
	if lines.size() < 8:
		return {"error": "POSCAR文件过短"}
	var scale = float(lines[1].strip_edges())
	var lat = []
	for i in range(2, 5):
		var parts = lines[i].strip_edges().split_floats(" ", false)
		if parts.size() >= 3:
			lat.append(Vector3(parts[0], parts[1], parts[2]))
	var type_line = lines[5].strip_edges()
	var count_line = lines[6].strip_edges()
	var types = type_line.split(" ", false)
	var counts = count_line.split_ints(" ", false)
	var coord_type = lines[7].strip_edges().to_lower()
	var is_cartesian = coord_type.begins_with("cart") or coord_type.begins_with("d")
	var atoms: Array = []
	var idx = 8
	for t in range(types.size()):
		var sym = _normalize_element(types[t])
		var n = counts[t] if t < counts.size() else 0
		for _i in range(n):
			if idx >= lines.size():
				break
			var parts = lines[idx].strip_edges().split_floats(" ", false)
			if parts.size() >= 3:
				var pos = Vector3(parts[0], parts[1], parts[2])
				if not is_cartesian and lat.size() == 3:
					pos = lat[0] * pos.x + lat[1] * pos.y + lat[2] * pos.z
				pos *= scale
				atoms.append({"symbol": sym, "position": pos})
			idx += 1
	return {"atoms": atoms, "bonds": []}

# === SDF/MOL 格式 (简化版) ===

static func export_sdf(atoms: Array, bonds: Array, title: String = "CQM") -> String:
	var lines: Array = []
	lines.append(title)
	lines.append("  CQMDesigner")
	lines.append("Comment")
	var n = atoms.size()
	var m = bonds.size()
	lines.append("%3d%3d  0  0  0  0  0  0  0  0999 V2000" % [n, m])
	for atom in atoms:
		var sym = _get_symbol(atom)
		var pos = _get_pos(atom)
		lines.append("%10.4f%10.4f%10.4f %-3s 0  0  0  0  0  0  0  0  0  0  0  0" % [pos.x, pos.y, pos.z, sym])
	for bond in bonds:
		var a_idx = _get_bond_atom_index(bond, 0) + 1
		var b_idx = _get_bond_atom_index(bond, 1) + 1
		var order = _get_bond_order(bond)
		lines.append("%3d%3d  %d  0  0  0  0" % [a_idx, b_idx, order])
	lines.append("M  END")
	lines.append("$$$$")
	return "\n".join(lines) + "\n"

static func import_sdf(text: String) -> Dictionary:
	var lines = text.split("\n")
	if lines.size() < 4:
		return {"error": "SDF文件过短"}
	var counts_line = lines[3]
	if counts_line.length() < 6:
		return {"error": "SDF计数行无效"}
	var n = int(counts_line.substr(0, 3))
	var m = int(counts_line.substr(3, 3))
	var atoms: Array = []
	for i in range(n):
		var line_idx = 4 + i
		if line_idx >= lines.size():
			break
		var line = lines[line_idx]
		if line.length() < 31:
			continue
		var x = float(line.substr(0, 10))
		var y = float(line.substr(10, 10))
		var z = float(line.substr(20, 10))
		var sym = line.substr(31, 3).strip_edges()
		sym = _normalize_element(sym)
		atoms.append({"symbol": sym, "position": Vector3(x, y, z)})
	var bonds: Array = []
	for i in range(m):
		var line_idx = 4 + n + i
		if line_idx >= lines.size():
			break
		var line = lines[line_idx]
		if line.length() < 6:
			continue
		var a_idx = int(line.substr(0, 3)) - 1
		var b_idx = int(line.substr(3, 3)) - 1
		var order = int(line.substr(6, 3)) if line.length() >= 9 else 1
		bonds.append({"a": a_idx, "b": b_idx, "order": order})
	return {"atoms": atoms, "bonds": bonds}

# === 通用导出接口 ===

static func export_to_format(atoms: Array, bonds: Array, fmt: String, path: String, options: Dictionary = {}) -> bool:
	var content = ""
	match fmt.to_lower():
		"xyz":
			content = export_xyz(atoms, bonds, options.get("comment", ""))
		"pdb":
			content = export_pdb(atoms, bonds, options.get("title", "CQM_STRUCTURE"))
		"cif":
			content = export_cif(atoms, bonds, options.get("cell", {}))
		"poscar", "vasp":
			content = export_poscar(atoms, options.get("cell", {}), options.get("comment", "CQM Structure"))
		"sdf", "mol":
			content = export_sdf(atoms, bonds, options.get("title", "CQM"))
		_:
			return false
	var file = FileAccess.open(path, FileAccess.WRITE)
	if not file:
		return false
	file.store_string(content)
	file.close()
	return true

static func import_from_file(path: String) -> Dictionary:
	var file = FileAccess.open(path, FileAccess.READ)
	if not file:
		return {"error": "无法打开文件: %s" % path}
	var text = file.get_as_text()
	file.close()
	var ext = path.get_extension().to_lower()
	match ext:
		"xyz":
			return import_xyz(text)
		"pdb":
			return import_pdb(text)
		"cif":
			return import_cif(text)
		"poscar", "vasp":
			return import_poscar(text)
		"sdf", "mol":
			return import_sdf(text)
		_:
			return {"error": "不支持的格式: %s" % ext}

# === 辅助函数 ===

static func _get_symbol(atom) -> String:
	if atom is Dictionary:
		return atom.get("symbol", "H")
	return atom.element_symbol

static func _get_pos(atom) -> Vector3:
	if atom is Dictionary:
		return atom.get("position", Vector3.ZERO)
	return atom.global_position

static func _get_bond_atom_index(bond, idx: int) -> int:
	if bond is Dictionary:
		var key = "a" if idx == 0 else "b"
		return int(bond.get(key, -1))
	if idx == 0:
		return bond.atom_a_idx if bond.get("atom_a_idx") != null else -1
	return bond.atom_b_idx if bond.get("atom_b_idx") != null else -1

static func _get_bond_order(bond) -> int:
	if bond is Dictionary:
		return int(bond.get("order", 1))
	return bond.bond_order if bond.get("bond_order") != null else 1

static func _normalize_element(sym: String) -> String:
	sym = sym.strip_edges()
	if sym.is_empty():
		return "H"
	if sym.length() == 1:
		return sym.to_upper()
	return sym[0].to_upper() + sym.substr(1).to_lower()

static func get_supported_formats() -> Dictionary:
	return {
		"import": ["xyz", "pdb", "cif", "poscar", "sdf", "mol"],
		"export": ["xyz", "pdb", "cif", "poscar", "sdf"],
		"descriptions": {
			"xyz": "XYZ 坐标文件",
			"pdb": "蛋白质数据库格式",
			"cif": "晶体学信息框架",
			"poscar": "VASP POSCAR 格式",
			"sdf": "结构数据文件 (SDF/MOL)",
			"mol": "MDL Mol 文件"
		}
	}
# === Quantum ESPRESSO pw.x 输入 (SCF 模板, ibrav=0) ===

## 由原子包围盒估计正交晶胞 (无显式晶格信息时的近似)
static func _estimate_cell(atoms: Array) -> Vector3:
	var mn := Vector3(INF, INF, INF)
	var mx := Vector3(-INF, -INF, -INF)
	for atom in atoms:
		var p = _get_pos(atom)
		mn = mn.min(p)
		mx = mx.max(p)
	var span = mx - mn
	var pad = 8.0  # 真空层 (孤立分子/团簇)
	return Vector3(maxf(span.x, 1.0) + pad, maxf(span.y, 1.0) + pad, maxf(span.z, 1.0) + pad)

static func export_qe_input(atoms: Array, title: String = "cqm_structure",
		options: Dictionary = {}) -> String:
	var cell = options.get("cell", _estimate_cell(atoms))
	var ecutwfc = options.get("ecutwfc", 60.0)
	var _nk = options.get("k_spacing_desc", "自动 (gamma 点, 分子/团簇)")
	var pseudo_map: Dictionary = options.get("pseudopotentials", {})
	var lines: Array = []
	lines.append("&CONTROL")
	lines.append("    calculation = 'scf'")
	lines.append("    prefix = '%s'" % title)
	lines.append("    outdir = './out'")
	lines.append("    pseudo_dir = './pseudo'")
	lines.append("/")
	lines.append("&SYSTEM")
	lines.append("    ibrav = 0")
	lines.append("    nat = %d" % atoms.size())
	lines.append("    ntyp = %d" % _count_types(atoms))
	lines.append("    ecutwfc = %.1f" % ecutwfc)
	lines.append("    occupations = 'smearing'")
	lines.append("    smearing = 'gaussian'")
	lines.append("    degauss = 0.02")
	lines.append("/")
	lines.append("&ELECTRONS")
	lines.append("    conv_thr = 1.0d-8")
	lines.append("    mixing_beta = 0.7")
	lines.append("/")
	lines.append("ATOMIC_SPECIES")
	var species = _type_order(atoms)
	for sym in species:
		var ed = ElementDB.get_element(sym)
		var mass = float(ed.get("atomic_mass", 1.0))
		var pseudo = str(pseudo_map.get(sym, "%s.UPF" % sym))
		lines.append("%s  %.4f  %s" % [sym, mass, pseudo])
	lines.append("CELL_PARAMETERS angstrom")
	lines.append("  %.6f  0.000000  0.000000" % cell.x)
	lines.append("  0.000000  %.6f  0.000000" % cell.y)
	lines.append("  0.000000  0.000000  %.6f" % cell.z)
	lines.append("ATOMIC_POSITIONS angstrom")
	for atom in atoms:
		var p = _get_pos(atom)
		lines.append("%s  %.6f  %.6f  %.6f" % [_get_symbol(atom), p.x, p.y, p.z])
	lines.append("K_POINTS automatic")
	lines.append("1 1 1 0 0 0")
	lines.append("")
	return "\n".join(lines)

static func _count_types(atoms: Array) -> int:
	return _type_order(atoms).size()

static func _type_order(atoms: Array) -> Array:
	var order: Array = []
	for atom in atoms:
		var sym = _get_symbol(atom)
		if not (sym in order):
			order.append(sym)
	return order
