name: lean
on:
  push:
    paths: ['08 理论组织和形式化框架/04_Lean对接/Lean源码/**']
  pull_request:
    paths: ['08 理论组织和形式化框架/04_Lean对接/Lean源码/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build-args: --wfail